### ISSUE TITLE
#f4e7ae4 | Compat

### ISSUE THREAD

**Issue by featherbear** [claudeheintz/LXDMXWiFi_Library#18]
Hi!

Using the library today, I had to make changes to https://github.com/claudeheintz/LXDMXWiFi_Library/blob/f4e7ae48b400004fb6de89cccccd57619f170d9c/src/LXWiFiSACN.cpp#L234
into ` if ( interfaceAddr ) {` due to compiler errors

---

Secondly, after investigating why my ArtNet packets weren't being received
I changed https://github.com/claudeheintz/LXDMXWiFi_Library/blob/f4e7ae48b400004fb6de89cccccd57619f170d9c/src/LXWiFiArtNet.cpp#L268
to `if ( _dmx_sender_a == INADDR_NONE ) {`  
(and likewise for `_dmx_sender_b`)

It seems that `INADDR_NONE` is equal to -1, not 0.

**but**, I've previously used this library in late 2017/early 2018 and it worked. 

Just wondering if you were aware of this, or it's some misconfiguration on my end

_PR: https://github.com/claudeheintz/LXDMXWiFi_Library/pull/19_

---

Commit f4e7ae4
NodeMCU V1 ESP8266
Arduino 1.8.9

**Comment by claudeheintz** [comment]
I believe this is clarified in the latest commit.  Also, this fixes the == comparison of IPAddress and 0 that throws a compile exception with the ESP8266 v2.5 board package.

**Comment by featherbear** [comment]
Yep, d88b3abd54ca737258d9923e5bcf054b256f34e8 fixes these issues

Thank you!
