### ISSUE TITLE
DMX2WiFi not work

### ISSUE THREAD

**Issue by folny** [claudeheintz/LXDMXWiFi_Library#3]
Hi

Today I tried the code DMX2WiFi which I have chosen ArtNet protocol but it does not work for me as I have chosen the input signal from FTDI as (Entec Open DMX) do not know where could be the problem ? when you connect a DMX signal LED flashes quickly but on the other device nothing happens.

**Comment by claudeheintz** [comment]
If the led on the 8266 flashes quickly when DMX is input, DMX2WiFi is likely working correctly.  You can use the DMX Input Test sketch from the LXESP8266DMX library to insure that the DMX input works correctly with your source and the circuit you have setup to convert DMX to serial input for the 8266.  If that is correct, the problem most likely lies in your network connection between the 8266 running DMX2WiFi and whatever you are receiving the Art-Net with.
