### ISSUE TITLE
Configuration utility multiple devices search

### ISSUE THREAD

**Issue by folny** [claudeheintz/LXDMXWiFi_Library#4]
Hi

I tested your code and it works perfectly but I am wondering whether it is a configuration utility that acts like a https://github.com/media-architecture/NodeUtil it would be great if they could find multiple devices in a single network, I think it would be useful for a better view and configure devices on the network.

**Comment by claudeheintz** [comment]
The configuration utility is part of an example using this library.  It is meant to show how the example's remote configuration scheme works, not be a complete project unto itself.  You could fork the NodeUtil you mention to also send and receive the configuration packets for the example.  The Java source code has been updated with an inner class that encapsulates a config packet and provides getter/setter methods for its fields.
