### ISSUE TITLE
ESP-DMX IP report porblem

### ISSUE THREAD

**Issue by digi128pci** [claudeheintz/LXDMXWiFi_Library#5]
Hi,
Firts of all very nice project!

I try to use Unicast.

I noticed a problem with some programs. The IP address was not recognised correctly.

The software I use is Lightjams.
The IP address in the programm is recognised as 0.0.0.0 ; When I change it to the correct IP it works.
The problem is when a node disconnects and reconnect the IP is changed to 0.0.0.0 and the system stops working.

I analyzed the problem in DMX workshop and noticed the following:

Artnet Report node:

![esp-artnet3](https://cloud.githubusercontent.com/assets/22595692/19043086/f308415e-898e-11e6-8599-917605044cf1.png)

In the node status and output routing it works ok.

![esp-artnet](https://cloud.githubusercontent.com/assets/22595692/19042835/ef059d46-898d-11e6-88f0-d92104aaed1d.png)

![esp-artnet2](https://cloud.githubusercontent.com/assets/22595692/19043090/f787c182-898e-11e6-897a-5a9eed35a98a.png)

![esp-artnet4](https://cloud.githubusercontent.com/assets/22595692/19043152/43f5e24c-898f-11e6-9c63-56c3f9b288d2.png)

I suspect that the IP is not defined in the node report.
Can I fix this in some way?

**Comment by claudeheintz** [comment]
The LXWiFiArtnet class has been updated to correctly return the local IP that is passed in the constructor.  (It was not doing this)  Also, should the IP address change, there is a new method
setLocalAddress that you can use that will update the poll reply with the new address.
