### ISSUE TITLE
Dmx wifi transmit & received.

### ISSUE THREAD

**Issue by mstevica** [claudeheintz/LXDMXWiFi_Library#7]
I see that there are many projects, but it is not clear.
I'd like to send dmx siglal 20 meters.
Would be to do a DMX transmitter and one DMX receiver .
It is not clear to me if it adjusts in the projects?
greeting

**Comment by claudeheintz** [comment]
This would work if you configure one microcontroller to convert DMX to Art-Net in access point WiFi mode .  Then, you configure another to convert Art-Net to DMX in WiFi station mode.  The second Art-Net receiver should be connected to the WiFi SSID created by the first (AP/sending) microcontroller.

**Comment by tapi35** [comment]
hello, 
mstevica, do you succeed creating a dmx transmitter and receiver ? I want to make the same but I don't understand wich lines I have to change.... could you help me a bit or send me your sketches ? Thanks a lot Have a good day
